apiVersion: apps/v1
kind: Deployment
metadata:
  name: priporocilni-sistemi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priporocilni-sistemi
  template:
    metadata:
      labels:
        app: priporocilni-sistemi
    spec:
      containers:
        - image: simenravnik/priporocilni-sistemi
          name: priporocilni-sistemi
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: priporocilni-sistemi
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: priporocilni-sistemi